<!-- :  INDENT FORM (button) -->

<form action="/" class="form-inside">
  <input type="text" maxlength="128" size="15" value="" name="search_block_form" id="edit-search-block-form--2" class="has-example form-text ui-autocomplete-input example indent" title="Søg efter materialer fra biblioteket.." autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true" />
  <div id="edit-actions" class="form-actions form-wrapper">
    <input type="submit" value="Search" name="op" id="edit-submit" class="btn btn-primary form-submit">
  </div>
</form>
