<!-- : Grid 4-4-4-4 -->
<div class="grid-wrapper">
  <div class="grid-inner">
    <div class="grid-row">
      <aside class="grid-4-left">
        <div class="grid-inner">grid-4-left</div>
      </aside>
      <aside class="grid-4-center-left">
        <div class="grid-inner">grid-4-center-left</div>
      </aside>
      <aside class="grid-4-center-right">
        <div class="grid-inner">grid-4-center-right</div>
      </aside>
      <aside class="grid-4-right">
        <div class="grid-inner">grid-4-right</div>
      </aside>
    </div>
  </div>
</div>