<!-- : Stacked grid 4-4-4-4 / 8-8 / 4-4-4-4 -->
<div class="grid-wrapper">
  <div class="grid-inner">
    <div class="grid-row">
      <aside class="grid-4-left">
        <div class="grid-inner">grid-4-left</div>
      </aside>
      <aside class="grid-4-center-left">
        <div class="grid-inner">grid-4-center-left</div>
      </aside>
      <aside class="grid-4-center-right">
        <div class="grid-inner">grid-4-center-right</div>
      </aside>
      <aside class="grid-4-right">
        <div class="grid-inner">grid-4-right</div>
      </aside>
    </div>
    <div class="grid-row">
      <div class="grid-8-left">
        <div class="grid-inner">grid-8-left</div>
      </div>
      <div class="grid-8-right">
        <div class="grid-inner">grid-8-right</div>
      </div>
    </div>
    <div class="grid-row last">
      <aside class="grid-4-left">
        <div class="grid-inner">grid-4-left</div>
      </aside>
      <aside class="grid-4-center-left">
        <div class="grid-inner">grid-4-center-left</div>
      </aside>
      <aside class="grid-4-center-right">
        <div class="grid-inner">grid-4-center-right</div>
      </aside>
      <aside class="grid-4-right">
        <div class="grid-inner">grid-4-right</div>
      </aside>
    </div>
  </div>
</div>