<!-- : Grid 4-4-8 -->
<div class="grid-wrapper">
  <div class="grid-inner">
    <div class="grid-row">
      <div class="grid-8-right">
        <div class="grid-inner">grid-8-right</div>
      </div>
      <aside class="grid-4-left">
        <div class="grid-inner">grid-4-left</div>
      </aside>
      <aside class="grid-4-center-left">
        <div class="grid-inner">grid-4-center-left</div>
      </aside>
    </div>
  </div>
</div>