  <footer class="grid-wrapper">
    <div class="grid-inner">
      <div class="grid-row-full">
        <div class="grid-content">
          <div class="grid-4-left">
            <h3 class="block-title">Footer 1</h3>
            <ul>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
            </ul>
          </div>
          <div class="grid-4-center-left">
            <h3 class="block-title">Footer 2</h3>
            <ul>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
            </ul>
          </div>
          <div class="grid-4-center-right">
            <h3 class="block-title">Footer 3</h3>
            <ul>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
            </ul>
          </div>
          <div class="grid-4-right">
            <h3 class="block-title">Footer 4</h3>
            <ul>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
              <li><a href="#" title="Link">Link</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>