<head>
  <title>Default Drupal Markup</title>
  <script type="text/javascript">
    $(function(){
        $("#tdcss").tdcss();
    })
  </script>
</head>
<body>
  <div class="grid-row">
    <div class="grid-3-left">
      <div class="grid-inner docs-sidebar">
        <ul class="nav nav-list docs-sidenav affix">
          <?php
            /*
             * The section id used for navigation is generated by tdcss.js
             * and use the tdcss section name lowercased and spaces replaced with -.
             *
             * ex. Base elements is base-elements.
             */
          ?>
          <li><a href="#typography"><i class="icon-chevron-right"></i> Typography</a></li>
          <li><a href="#alerts"><i class="icon-chevron-right"></i> Alerts</a></li>
          <li><a href="#images"><i class="icon-chevron-right"></i> Images</a></li>
          <li><a href="#menus"><i class="icon-chevron-right"></i> Menus</a></li>
          <li><a href="#tables"><i class="icon-chevron-right"></i> Tables</a></li>
          <li><a href="#forms"><i class="icon-chevron-right"></i> Forms</a></li>
        </ul>
      </div>
    </div>
    <div class="grid-13-right">
      <div class="grid-inner">
        <div id="tdcss">
          <?php include_once('drupal-markup/typography.php'); ?>
          <?php include_once('drupal-markup/alerts.php'); ?>
          <?php include_once('drupal-markup/images.php'); ?>
          <?php include_once('drupal-markup/menus.php'); ?>
          <?php include_once('drupal-markup/tables.php'); ?>
          <?php include_once('drupal-markup/forms.php'); ?>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
  <script src="src/vendors/bootstrap-scrollspy.js"></script>
  <script src="src/vendors/google-code-prettify/prettify.js"></script>
</body>