<head>
  <title>Markup Guidelines</title>
  <script type="text/javascript">
    $(function(){
        $("#tdcss").tdcss();
    })
  </script>
</head>
<body>
  <div class="grid-row">
    <div class="grid-3-left">
      <div class="grid-inner docs-sidebar">
        <ul class="nav nav-list docs-sidenav affix">
          <?php
            /*
             * The section id used for navigation is generated by tdcss.js
             * and use the tdcss section name lowercased and spaces replaced with -.
             *
             * ex. Base elements is base-elements.
             */
          ?>
          <li class="active"><a href="#base-elements"><i class="icon-chevron-right"></i> Base elements</a></li>
          <li><a href="#typography"><i class="icon-chevron-right"></i> Typography</a></li>
          <li><a href="#forms"><i class="icon-chevron-right"></i> Forms</a></li>
          <li><a href="#buttons"><i class="icon-chevron-right"></i> Buttons</a></li>
          <li><a href="#tables"><i class="icon-chevron-right"></i> Tables</a></li>
          <li><a href="#pagers"><i class="icon-chevron-right"></i> Pagers</a></li>
          <li><a href="#pagination"><i class="icon-chevron-right"></i> Pagination</a></li>
          <li><a href="#labels"><i class="icon-chevron-right"></i> Labels</a></li>
          <li><a href="#lists"><i class="icon-chevron-right"></i> Lists</a></li>
          <li><a href="#tabs"><i class="icon-chevron-right"></i> Tabs</a></li>
          <li><a href="#grid-system"><i class="icon-chevron-right"></i> Grid system</a></li>
          <li><a href="#miscellaneous"><i class="icon-chevron-right"></i> Miscellaneous</a></li>
        </ul>
      </div>
    </div>
    <div class="grid-13-right">
      <div class="grid-inner">
        <div id="tdcss">
          <?php
            foreach(scandir('markup') as $file) {
              if (strpos($file, '.inc') > 0) {
                include_once('markup/' . $file);
              }
            }
          ?>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
  <script src="src/vendors/bootstrap-scrollspy.js"></script>
  <script src="src/vendors/google-code-prettify/prettify.js"></script>
</body>