<?php
  $plugin['layout_template_default'] = array(
    'title'     => t('Latto default template, FOOOO'),
    'icon'      => 'layout_template_default.png',
    'theme'     => 'layout_template_default',
    'category'  => 'Latto framework',
    'regions'   => array(
      'primary_content'   => t('Primary content'),
      'secondary_content' => t('Secondary content'),
      'tertiary_content'  => t('Tertiary content'),
      'attachment_first'  => t('Attachment 1'),
      'attachment_second' => t('Attachment 2'),
      'attachment_third'  => t('Attachment 3'),
      'attachment_fourth' => t('Attachment 4'),
    ),
  );
