<?php
$plugin['full_8_4_4_stacked'] = array(
  'title' => t('Top row full, three columns 8-4-4'),
  'icon' => 'full_8_4_4_stacked.png',
  'theme' => 'full_8_4_4_stacked',
  'category'  => 'Latto - multiple rows, three columns',
  'regions' => array(
    'grid_16_top_full' => t('Top content'),
    'grid_8_left' => t('Left content'),
    'grid_4_center_right' => t('Right inner sidebar'),
    'grid_4_right' => t('Right sidebar'),
  ),
);
