<!-- : FOOTER MENU -->

<h3 class="block-title">Footer menu</h3>
<ul>
  <li><a href="#" title="Adgang for alle">Adgang for alle</a></li>
  <li><a href="#" title="Bibliotekets Nyhedsliste">Bibliotekets Nyhedsliste</a></li>
  <li><a href="#" title="FAQ - sådan gør du">FAQ - sådan gør du</a></li>
  <li><a href="#" title="Nyhedslister">Nyhedslister</a></li>
  <li><a href="#" title="Publikationer">Publikationer</a></li>
  <li><a href="#" title="Temalister">Temalister</a></li>
</ul>