<!-- : MAIN MENU -->

<ul class="main-menu nav nav-inline">
  <li class="first active" style="width: 236px;"><span><a class="active" title="" href="/">Forsiden</a></span></li>
  <li style="width: 236px;"><span><a href="/events">Events</a></span></li>
  <li style="width: 236px;"><span><a href="/libraries">Libraries</a></span></li>
  <li style="width: 236px;"><span><a href="/news">News</a></span></li>
  <li class="last" style="width: 236px;"><span><a href="/page/kan">Det kan du</a></span></li>
</ul>
