<!-- : SEARCH FORM -->

<form accept-charset="UTF-8" id="search-block-form" method="post" action="/" class="form-inside">
  <div>
    <h2 class="element-invisible">Search form</h2>
    <div class="form-item form-type-textfield form-item-search-block-form">
      <label for="edit-search-block-form--2" class="element-invisible">Search</label>
      <i class="icon-search"></i>
      <input type="text" maxlength="128" size="15" value="" name="search_block_form" id="edit-search-block-form--2" class="has-example form-text ui-autocomplete-input example indent" title="Søg efter materialer fra biblioteket.." autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true" />
      <div id="edit-actions" class="form-actions form-wrapper">
        <input type="submit" value="Search" name="op" id="edit-submit" class="btn btn-primary form-submit">
      </div>
    </div>
    <input type="hidden" value="form-iEXKcmcap-BsYSQjt_cPnRNti2wZeNEsOASFNM1EoBM" name="form_build_id">
    <input type="hidden" value="search_block_form" name="form_id">
    <input type="hidden" value="" name="sort" id="controls_search_sort">
    <input type="hidden" value="" name="size" id="controls_search_size">
  </div>
</form>
