<!-- : CAROUSEL -->

<!-- The wrapper div is important because rs-carousel replaces it -->
<div class="rs-carousel-wrapper rs-carousel-wide">
  <div class="rs-carousel rs-carousel-horizontal rs-carousel-items-auto" aria-disabled="false">
    <div class="rs-carousel-inner">
      <div class="ajax-loader element-hidden"></div>
      <div class="rs-carousel-title">Harry Potter</div>
      <div class="rs-carousel-mask">
        <ul class="rs-carousel-runner" style="width: 1680px; left: 0px; ">
          <li class="rs-carousel-item">
            <a href="ting/collection/775100:27267912" class="rs-carousel-item-image"><img src="http://ding2tal.ting.dk/sites/default/files/styles/ting_search_carousel/public/ting_search_carousel/d2f313989e4afe6c371c960d81d46854.jpg" alt=""></a>
            <a href="ting/collection/775100:27267912" class="rs-carousel-item-title">Harry Potter og dødsregalierne</a>
          </li>
          <li class="rs-carousel-item">
            <a href="ting/collection/775100:29316910" class="rs-carousel-item-image"><img src="http://ding2tal.ting.dk/sites/default/files/styles/ting_search_carousel/public/ting_search_carousel/e584b62f717b4fcd9ef5754796294403.jpg" alt=""></a>
            <a href="ting/collection/775100:29316910" class="rs-carousel-item-title">Harry Potter og dødsregalierne</a>
          </li>
          <li class="rs-carousel-item">
            <a href="ting/collection/775100:26917921" class="rs-carousel-item-image"><img src="http://ding2tal.ting.dk/sites/default/files/styles/ting_search_carousel/public/ting_search_carousel/8ca26db5f8aa5322041330d5fbe4633c.jpg" alt=""></a>
            <a href="ting/collection/775100:26917921" class="rs-carousel-item-title">Harry Potter og dødsregalierne</a>
          </li>
          <li class="rs-carousel-item">
            <a href="ting/collection/775100:28744129" class="rs-carousel-item-image"><img src="http://ding2tal.ting.dk/sites/default/files/styles/ting_search_carousel/public/ting_search_carousel/b9938c9af24d99ba5095aa790187e566.jpg" alt=""></a>
            <a href="ting/collection/775100:28744129" class="rs-carousel-item-title">Harry Potter and the deathly hallows - part 1</a>
          </li>
          <li class="rs-carousel-item">
            <a href="ting/collection/775100:28529724" class="rs-carousel-item-image"><img src="http://ding2tal.ting.dk/sites/default/files/styles/ting_search_carousel/public/ting_search_carousel/41e4590e38efe411d6b2b318d3cc9a1d.jpg" alt=""></a>
            <a href="ting/collection/775100:28529724" class="rs-carousel-item-title">Harry Potter and the deathly hallows - part 1</a>
          </li>
          <li class="rs-carousel-item">
            <a href="ting/collection/775100:28870671" class="rs-carousel-item-image"><img src="http://ding2tal.ting.dk/sites/default/files/styles/ting_search_carousel/public/ting_search_carousel/75d374dfda51e720e30ca16ec0d6f8d0.jpg" alt=""></a>
            <a href="ting/collection/775100:28870671" class="rs-carousel-item-title">Harry Potter and the deathly hallows - part 2</a>
          </li>
          <li class="rs-carousel-item">
            <a href="ting/collection/775100:29114668" class="rs-carousel-item-image"><img src="http://ding2tal.ting.dk/sites/default/files/styles/ting_search_carousel/public/ting_search_carousel/09797524469a3a251e382166a299dcef.jpg" alt=""></a>
            <a href="ting/collection/775100:29114668" class="rs-carousel-item-title">Harry Potter and the deathly hallows - part 2</a>
          </li>
          <li class="rs-carousel-item">
            <a href="ting/collection/775100:29317038" class="rs-carousel-item-image"><img src="http://ding2tal.ting.dk/sites/default/files/styles/ting_search_carousel/public/ting_search_carousel/cda2d94d5ae0e31ed61f9d8615624ded.jpg" alt=""></a>
            <a href="ting/collection/775100:29317038" class="rs-carousel-item-title">Harry Potter og De Vises Sten</a>
          </li>
          <li class="rs-carousel-item">
            <a href="ting/collection/775100:25194853" class="rs-carousel-item-image"><img src="http://ding2tal.ting.dk/sites/default/files/styles/ting_search_carousel/public/ting_search_carousel/0ff76bbd78cffb7361cf3f69617c35d1.jpg" alt=""></a>
            <a href="ting/collection/775100:25194853" class="rs-carousel-item-title">Harry Potter og De Vises Sten</a>
          </li>
          <li class="rs-carousel-item">
            <a href="ting/collection/775100:22252852" class="rs-carousel-item-image"><img src="http://ding2tal.ting.dk/sites/default/files/styles/ting_search_carousel/public/ting_search_carousel/00ec87c28d71e8db45d141f2938102aa.jpg" alt=""></a>
            <a href="ting/collection/775100:22252852" class="rs-carousel-item-title">Harry Potter og De Vises Sten</a>
          </li>
          <li class="rs-carousel-item">
            <a href="ting/collection/775100:22629344" class="rs-carousel-item-image"><img src="http://ding2tal.ting.dk/sites/default/files/styles/ting_search_carousel/public/ting_search_carousel/13d8cb4abc48d3d1cf1c191c9c926535.jpg" alt=""></a>
            <a href="ting/collection/775100:22629344" class="rs-carousel-item-title">Harry Potter og De Vises Sten</a>
          </li>
          <li class="rs-carousel-item">
            <a href="ting/collection/775100:28527454" class="rs-carousel-item-image"><img src="http://ding2tal.ting.dk/sites/default/files/styles/ting_search_carousel/public/ting_search_carousel/b0d8805ce46f21e845ac0058c3a6ab21.jpg" alt=""></a>
            <a href="ting/collection/775100:28527454" class="rs-carousel-item-title">Harry Potter and the deathly hallows - part 1</a>
          </li>
          <li class="rs-carousel-item">
            <a href="ting/collection/775100:28527276" class="rs-carousel-item-image"><img src="http://ding2tal.ting.dk/sites/default/files/styles/ting_search_carousel/public/ting_search_carousel/798fc53a3f537c6b37408a5c2138d8ab.jpg" alt=""></a>
            <a href="ting/collection/775100:28527276" class="rs-carousel-item-title">Harry Potter and the deathly hallows - part 1</a>
          </li>
          <li class="rs-carousel-item">
            <a href="ting/collection/775100:28527373" class="rs-carousel-item-image"><img src="http://ding2tal.ting.dk/sites/default/files/styles/ting_search_carousel/public/ting_search_carousel/ab181d7927320150df2845e794553c33.jpg" alt=""></a>
            <a href="ting/collection/775100:28527373" class="rs-carousel-item-title">Harry Potter and the deathly hallows - part 1</a>
          </li>
        </ul>
      </div>
      <ol class="rs-carousel-pagination">
        <li class="rs-carousel-pagination-link rs-carousel-pagination-link-active">
          <a href="#page-1">1</a>
        </li>
        <li class="rs-carousel-pagination-link">
          <a href="#page-2">2</a>
        </li>
        <li class="rs-carousel-pagination-link">
          <a href="#page-3">3</a>
        </li>
      </ol>
    </div>

    <!-- Only print tabs if there is more than 1 -->
    <div class="rs-carousel-tabs">
      <ul>
        <li class="active" style="width: 295px; ">
          <a href="#">Harry Potter</a>
        </li>
        <li class="" style="width: 295px; ">
          <a href="#">Isabel Allende</a>
        </li>
        <li class="" style="width: 295px; ">
          <a href="#">Skole start</a>
        </li>
        <li class="" style="width: 295px; ">
          <a href="#">Olympiske Lege</a>
        </li>
      </ul>
    </div>
  </div>
</div>
