<?php
$plugin['full_10_3_3_stacked'] = array(
  'title' => t('Top row full, three columns 10-3-3'),
  'icon' => 'full_10_3_3_stacked.png',
  'theme' => 'full_10_3_3_stacked',
  'category'  => 'Latto - multiple rows, three columns',
  'regions' => array(
    'grid_16_top_full' => t('Top content'),
    'grid_10_left' => t('Left content'),
    'grid_3_center_right' => t('Right inner sidebar'),
    'grid_3_right' => t('Right sidebar'),
  ),
);
