<!-- : LIST DIV WITH ICONS (date-list) -->
<div class="date-list">
  <div class="list-item">
    <h3 class="heading"><a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit...</a></h3>
    <div class="date-wrapper">
      <div class="day">Onsdag</div>
      <div class="date-wrapper-inner">
	      <div class="date">8</div>
        <div class="month">AUG</div>
      </div>
    </div>
    <div class="content">      
      <p><i class="icon-home"></i> Biblioteket</p>
      <p><i class="icon-time"></i> 10.00 - 11.00</p>
      <p><i class="icon-credit-card"></i> Kr. 20,-</p>
    </div>
  </div>
  <div class="list-item">
    <h3 class="heading"><a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit...</a></h3>
    <div class="date-wrapper">
      <div class="day">Onsdag</div>
      <div class="date-wrapper-inner">
	      <div class="date">8</div>
        <div class="month">AUG</div>
      </div>
    </div>
    <div class="content">      
      <p><i class="icon-home"></i> Biblioteket</p>
      <p><i class="icon-time"></i> 10.00 - 11.00</p>
      <p><i class="icon-credit-card"></i> Kr. 20,-</p>
    </div>
  </div>
  <div class="list-item">
    <h3 class="heading"><a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit...</a></h3>
    <div class="date-wrapper">
      <div class="day">Onsdag</div>
      <div class="date-wrapper-inner">
	      <div class="date">8</div>
        <div class="month">AUG</div>
      </div>
    </div>
    <div class="content">      
      <p><i class="icon-home"></i> Biblioteket</p>
      <p><i class="icon-time"></i> 10.00 - 11.00</p>
      <p><i class="icon-credit-card"></i> Kr. 20,-</p>
    </div>
  </div>
  <div class="list-item last">
    <h3 class="heading"><a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit...</a></h3>
    <div class="date-wrapper">
      <div class="day">Onsdag</div>
      <div class="date-wrapper-inner">
	      <div class="date">8</div>
        <div class="month">AUG</div>
      </div>
    </div>
    <div class="content">      
      <p><i class="icon-home"></i> Biblioteket</p>
      <p><i class="icon-time"></i> 10.00 - 11.00</p>
      <p><i class="icon-credit-card"></i> Kr. 20,-</p>
    </div>
  </div>
</div>

