<!-- : LIST COMPACT -->
<ul class="list-compact">
  <li>
    <span class="list-date">10. aug</span>
    <h3 class="list-heading">
      <a href="#">Etiam Vehicula Porta Egestas</a>
    </h3>
  </li>
  <li>
    <h3 class="list-heading">
      <a href="#">Vehicula Justo</a>
    </h3>
  </li>
  <li>
    <h3 class="list-heading">
      <a href="#">Bibendum Sit Tellus Amet Fringilla</a>
    </h3>
  </li>
  <li>
    <span class="list-date">8. jul</span>
    <h3 class="list-heading">
      <a href="#">Aenean lacinia bibendum nulla sed consectetur. Vestibulum id ligula porta felis euismod semper.</a>
    </h3>
  </li>
  <li class="last">
    <span class="list-date">22. sep</span>
    <h3 class="list-heading">
      <a href="#">Bibendum Sit Tellus Amet Fringilla</a>
    </h3>
  </li>
</ul>

