<!-- : NEWS LIST -->
<ul class="list-news">
  <li>
    <h3 class="list-heading">
      <a href="#">Lorum Ipsum</a>
    </h3>
    <div class="list-meta">
      <span class="list-label"><a href="#">Lorem</a></span>
      <span class="list-date">10. august 2012</span>
      <span class="list-author">af <a href="#" title="View user profile." class="list-username">Author name</a></span>
    </div>
    <div class="list-image-inline">
      <a href="#"><img src="http://lorempixel.com/100/100/city/" /></a>
    </div>
    <p class="list-content">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit...
    </p>
    <a href="#">Read more</a>
  </li>
  <li>
    <h3 class="list-heading">
      <a href="#">Lorum Ipsum</a>
    </h3>
    <div class="list-meta">
      <span class="list-label"><a href="#">Lorem</a></span>
      <span class="list-date">10. august 2012</span>
      <span class="list-author">af <a href="#" title="View user profile." class="list-username">Author name</a></span>
    </div>
    <p class="list-content">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit...
    </p>
    <a href="#">Read more</a>
  </li>
  <li class="list-last">
    <h3 class="list-heading">
      <a href="#">Lorum Ipsum</a>
    </h3>
    <div class="list-meta">
      <span class="list-label"><a href="#">Lorem</a></span>
      <span class="list-date">10. august 2012</span>
      <span class="list-author">af <a href="#" title="View user profile." class="list-username">Author name</a></span>
    </div>
    <div class="list-image-inline">
      <a href="#"><img src="http://lorempixel.com/100/100/city/" /></a>
    </div>
    <p class="list-content">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit...
    </p>
    <a href="#">Read more</a>
  </li>
</ul>

