<!-- : LIST (default) -->
<ul class="list">
  <li class="list-item">
    <h3 class="heading">
      <a href="#">Lorum Ipsum</a>
    </h3>
    <div class="meta">
      <span class="label label-info"><a href="#">Lorem</a></span>
      <span class="date">10. august 2012</span>
      <span class="author">af <a href="#" title="View user profile." class="username">Author name</a></span>
    </div>
    <div class="image-container">
      <a href="#"><img src="http://lorempixel.com/800/200/city/" /></a>
    </div>
    <p class="content">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit...
    </p>
    <a href="#">Read more</a>
  </li>
  <li class="list-item">
    <h3 class="heading">
      <a href="#">Lorum Ipsum</a>
    </h3>
    <div class="meta">
      <span class="label label-info"><a href="#">Lorem</a></span>
      <span class="date">10. august 2012</span>
      <span class="author">af <a href="#" title="View user profile." class="username">Author name</a></span>
    </div>
    <p class="content">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit...
    </p>
    <a href="#">Read more</a>
  </li>
  <li class="list-item last">
    <h3 class="heading">
      <a href="#">Lorum Ipsum</a>
    </h3>
    <div class="meta">
      <span class="label label-info"><a href="#">Lorem</a></span>
      <span class="date">10. august 2012</span>
      <span class="author">af <a href="#" title="View user profile." class="username">Author name</a></span>
    </div>
    <div class="image-container">
      <a href="#"><img src="http://lorempixel.com/800/200/city/" /></a>
    </div>
    <p class="content">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit...
    </p>
    <a href="#">Read more</a>
  </li>
</ul>

