<!-- : LIST CALENDAR WITH ICONS -->
<ul class="list-calendar">
  <li>
    <h3 class="list-heading"><a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit...</a></h3>
    <div class="list-date-wrapper">
      <div class="list-day">Onsdag</div>
      <div class="list-date-wrapper-inner">
	      <div class="list-date">8</div>
        <div class="list-month">AUG</div>
      </div>
    </div>
    <div class="list-content">      
      <p><i class="icon-home"></i>Biblioteket</p>
      <p><i class="icon-time"></i>10.00 - 11.00</p>
      <p><i class="icon-credit-card"></i>Kr. 20,-</p>
    </div>
  </li>
  <li>
    <h3 class="list-heading"><a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit...</a></h3>
    <div class="list-date-wrapper">
      <div class="list-day">Onsdag</div>
      <div class="list-date-wrapper-inner">
	      <div class="list-date">8</div>
        <div class="list-month">AUG</div>
      </div>
    </div>
    <div class="list-content">      
      <p><i class="icon-home"></i>Biblioteket</p>
      <p><i class="icon-time"></i>10.00 - 11.00</p>
      <p><i class="icon-credit-card"></i>Kr. 20,-</p>
    </div>
  </li>
  <li>
    <h3 class="list-heading"><a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit...</a></h3>
    <div class="list-date-wrapper">
      <div class="list-day">Onsdag</div>
      <div class="list-date-wrapper-inner">
	      <div class="list-date">8</div>
        <div class="list-month">AUG</div>
      </div>
    </div>
    <div class="list-content">      
      <p><i class="icon-home"></i>Biblioteket</p>
      <p><i class="icon-time"></i>10.00 - 11.00</p>
      <p><i class="icon-credit-card"></i>Kr. 20,-</p>
    </div>
  </li>
  <div class="list-list-item last">
    <h3 class="list-heading"><a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit...</a></h3>
    <div class="list-date-wrapper">
      <div class="list-day">Onsdag</div>
      <div class="list-date-wrapper-inner">
	      <div class="list-date">8</div>
        <div class="list-month">AUG</div>
      </div>
    </div>
    <div class="list-content">      
      <p><i class="icon-home"></i>Biblioteket</p>
      <p><i class="icon-time"></i>10.00 - 11.00</p>
      <p><i class="icon-credit-card"></i>Kr. 20,-</p>
    </div>
  </li>
</ul>

