<!-- : LIST (date-list compact) -->
<ul class="list-compact">
  <li class="list-item">
    <span class="date">10. aug</span>
    <h3 class="heading">
      <a href="#">Etiam Vehicula Porta Egestas</a>
    </h3>
  </li>
  <li class="list-item">
    <h3 class="heading">
      <a href="#">Vehicula Justo</a>
    </h3>
  </li>
  <li class="list-item">
    <h3 class="heading">
      <a href="#">Bibendum Sit Tellus Amet Fringilla</a>
    </h3>
  </li>
  <li class="list-item">
    <span class="date">8. jul</span>
    <h3 class="heading">
      <a href="#">Aenean lacinia bibendum nulla sed consectetur. Vestibulum id ligula porta felis euismod semper.</a>
    </h3>
  </li>
  <li class="list-item last">
    <span class="date">22. sep</span>
    <h3 class="heading">
      <a href="#">Bibendum Sit Tellus Amet Fringilla</a>
    </h3>
  </li>
</ul>

