<!-- : LIST CALENDAR -->
<ul class="list-calendar">
  <li>
    <h3 class="list-heading"><a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit...</a></h3>
    <div class="list-date-wrapper">
      <div class="list-day">Onsdag</div>
      <div class="list-date-wrapper-inner">
	      <div class="list-date">8</div>
        <div class="list-month">AUG</div>
      </div>
    </div>
    <div class="list-content">      
      <p>Sted: Biblioteket</p>
      <p>Tidspunkt: 10.00 - 11.00</p>
      <p>Pris: Kr. 20,-</p>
    </div>
  </li>
  <li>
    <h3 class="list-heading"><a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit...</a></h3>
    <div class="list-date-wrapper">
      <div class="list-day">Onsdag</div>
      <div class="list-date-wrapper-inner">
	      <div class="list-date">8</div>
        <div class="list-month">AUG</div>
      </div>
    </div>
    <div class="list-content">      
      <p>Sted: Biblioteket</p>
      <p>Tidspunkt: 10.00 - 11.00</p>
      <p>Pris: Kr. 20,-</p>
    </div>
  </li>
  <li>
    <h3 class="list-heading"><a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit...</a></h3>
    <div class="list-date-wrapper">
      <div class="list-day">Onsdag</div>
      <div class="list-date-wrapper-inner">
	      <div class="list-date">8</div>
        <div class="list-month">AUG</div>
      </div>
    </div>
    <div class="list-content">      
      <p>Sted: Biblioteket</p>
      <p>Tidspunkt: 10.00 - 11.00</p>
      <p>Pris: Kr. 20,-</p>
    </div>
  </li>
  <li class="list-list-item last">
    <h3 class="list-heading"><a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit...</a></h3>
    <div class="list-date-wrapper">
      <div class="list-day">Onsdag</div>
      <div class="list-date-wrapper-inner">
	      <div class="list-date">8</div>
        <div class="list-month">AUG</div>
      </div>
    </div>
    <div class="list-content">      
      <p>Sted: Biblioteket</p>
      <p>Tidspunkt: 10.00 - 11.00</p>
      <p>Pris: Kr. 20,-</p>
    </div>
  </li>
</ul>

