<?php
$plugin['four_4_4_4_4'] = array(
  'title' => t('Four Columns, 4-4-4-4'),
  'icon' => 'four_4_4_4_4.png',
  'theme' => 'four_4_4_4_4',
  'category'  => 'Latto - single row, four columns',
  'regions' => array(
    'grid_4_left' => t('Left Sidebar'),
    'grid_4_center_left' => t('Left Inner Content'),
    'grid_4_center_right' => t('Right Inner Content'),
    'grid_4_right' => t('Right Sidebar'),
  ),
);
