<?php
$plugin['bricks_8_8_stacked'] = array(
  'title' => t('Bricks, two columns 8-8'),
  'icon' => 'bricks_8_8_stacked.png',
  'theme' => 'bricks_8_8_stacked',
  'category'  => 'Latto - multiple rows, two columns',
  'regions' => array(
    'grid_4_top_left' => t('Top left sidebar'),
    'grid_4_top_center_left' => t('Top left inner content'),
    'grid_4_top_center_right' => t('Top right inner content'),
    'grid_4_top_right' => t('Top right sidebar'), 
    'grid_8_left' => t('Left content'),
    'grid_8_right' => t('Right content'),
    'grid_4_bottom_left' => t('Bottom left sidebar'),
    'grid_4_bottom_center_left' => t('Bottom left inner content'),
    'grid_4_bottom_center_right' => t('Bottom right inner content'),
    'grid_4_bottom_right' => t('Bottom right sidebar'),
  ),
);
